In [1]:
# Import the dependencies
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv('weather_data/cities.csv')
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Cape Town,ZA,2020-12-02 01:56:18,-33.93,18.42,61.00,62,20,13.87
1,1,Kununurra,AU,2020-12-02 01:58:15,-15.77,128.73,86.00,66,98,4.70
2,2,Ushuaia,AR,2020-12-02 01:57:40,-54.80,-68.30,37.40,94,40,17.22
3,3,Tasiilaq,GL,2020-12-02 01:58:16,65.61,-37.64,19.40,57,100,18.34
4,4,Qaanaaq,GL,2020-12-02 01:58:16,77.48,-69.36,-0.76,88,100,8.66

In [3]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
# Get the maximum temperature.
max_temp = city_data_df['Max Temp']

temps = [max(temp, 0) for temp in max_temp]

In [6]:
temps

[61.0,
 86.0,
 37.4,
 19.4,
 0,
 28.56,
 69.85,
 13.33,
 71.6,
 67.64,
 80.6,
 38.98,
 28.4,
 46.99,
 62.6,
 77.76,
 75.81,
 78.8,
 0,
 39.2,
 57.99,
 57.0,
 32.0,
 62.1,
 84.2,
 37.4,
 59.0,
 39.2,
 48.2,
 76.06,
 82.4,
 87.01,
 85.26,
 60.8,
 19.4,
 80.6,
 24.8,
 98.6,
 66.22,
 39.99,
 83.41,
 28.4,
 39.99,
 76.44,
 89.6,
 11.34,
 57.0,
 77.0,
 41.0,
 61.97,
 77.0,
 30.2,
 93.2,
 80.6,
 62.6,
 0,
 48.2,
 79.0,
 64.4,
 47.25,
 75.99,
 20.62,
 82.4,
 48.2,
 41.0,
 73.36,
 86.54,
 61.0,
 73.36,
 66.2,
 73.98,
 0,
 85.78,
 61.0,
 82.72,
 51.01,
 71.17,
 80.6,
 75.2,
 53.6,
 24.8,
 62.42,
 1.4,
 62.35,
 78.49,
 82.4,
 76.35,
 77.0,
 76.48,
 0.81,
 48.2,
 74.62,
 86.61,
 67.51,
 30.0,
 78.8,
 75.67,
 73.4,
 39.78,
 32.18,
 25.84,
 57.99,
 35.6,
 77.0,
 80.01,
 17.6,
 78.35,
 89.6,
 82.17,
 64.99,
 80.6,
 30.18,
 53.6,
 39.2,
 0,
 64.99,
 21.92,
 34.0,
 73.58,
 78.42,
 71.01,
 78.8,
 76.77,
 60.08,
 48.2,
 24.8,
 0,
 44.6,
 75.06,
 62.87,
 55.0,
 75.2,
 19.4,
 63.77,
 14.0,
 77.2,
 71.53,
 78.01,
 31.08,
 62.49,
 0,
 17.96,
 1.4,
 61.74,
 32.18,
 83.91,
 75.99,
 41.0,
 72.5,
 21.2,
 57.99,
 68.7,
 10.56,
 0,
 85.39,
 29.97,
 55.4,
 77.0,
 66.99,
 83.37,
 51.8,
 82.4,
 51.8,
 32.0,
 73.99,
 57.99,
 77.0,
 7.81,
 91.0,
 48.2,
 62.28,
 82.06,
 55.4,
 83.98,
 3.2,
 7.29,
 57.2,
 57.2,
 79.0,
 22.86,
 84.09,
 0,
 42.01,
 36.0,
 91.99,
 77.86,
 67.32,
 83.3,
 70.52,
 81.07,
 65.44,
 48.83,
 0,
 44.01,
 46.04,
 75.99,
 79.95,
 35.01,
 55.45,
 77.0,
 15.8,
 64.4,
 43.0,
 46.99,
 27.79,
 66.79,
 28.56,
 29.53,
 81.86,
 68.0,
 55.99,
 5.07,
 46.4,
 75.13,
 95.58,
 86.0,
 0,
 15.8,
 56.93,
 58.5,
 77.5,
 8.94,
 93.2,
 61.09,
 37.4,
 70.0,
 86.0,
 68.0,
 39.99,
 82.4,
 1.29,
 77.0,
 5.0,
 26.6,
 52.09,
 60.31,
 3.2,
 33.8,
 82.38,
 77.16,
 54.0,
 73.47,
 54.45,
 67.95,
 40.08,
 24.8,
 29.7,
 46.0,
 63.0,
 80.6,
 73.99,
 45.0,
 0,
 0,
 82.4,
 81.64,
 75.0,
 73.4,
 75.36,
 53.6,
 46.4,
 76.12,
 50.0,
 35.01,
 55.4,
 59.0,
 53.01,
 55.4,
 76.06,
 74.89,
 14.0,
 23.92,
 85.28,
 37.4,
 77.0,
 46.4,
 84.97,
 48.2,
 55.4,
 37.4,
 77.0,
 55.0,
 77.0,
 75.49,
 66.2,
 28.4,
 69.8,
 37.4,
 55.4,
 32.0,
 78.8,
 76.44,
 66.2,
 99.03,
 28.9,
 75.2,
 73.4,
 72.46,
 0,
 41.0,
 28.17,
 48.99,
 0,
 55.0,
 75.76,
 3.99,
 85.82,
 14.0,
 74.35,
 67.84,
 37.4,
 62.91,
 83.03,
 79.0,
 35.6,
 60.8,
 13.93,
 51.8,
 38.44,
 52.75,
 30.2,
 37.99,
 64.53,
 14.0,
 44.01,
 26.76,
 82.89,
 53.6,
 77.0,
 24.8,
 46.4,
 44.01,
 39.9,
 59.0,
 43.0,
 41.18,
 55.96,
 82.4,
 73.4,
 81.0,
 41.0,
 42.01,
 3.2,
 73.4,
 29.79,
 21.2,
 62.01,
 55.0,
 80.6,
 60.8,
 9.84,
 77.0,
 9.82,
 69.51,
 35.6,
 71.92,
 46.0,
 65.57,
 78.13,
 2.14,
 48.6,
 36.0,
 66.2,
 41.0,
 85.08,
 21.81,
 42.01,
 8.08,
 55.0,
 63.0,
 71.6,
 62.6,
 82.0,
 35.01,
 41.0,
 16.48,
 46.4,
 72.68,
 64.0,
 83.7,
 73.6,
 74.53,
 55.4,
 64.4,
 35.6,
 70.39,
 0,
 58.23,
 83.17,
 44.01,
 60.01,
 62.56,
 46.99,
 69.66,
 0,
 74.7,
 61.0,
 19.4,
 77.0,
 37.4,
 45.0,
 81.54,
 78.42,
 74.43,
 73.4,
 77.0,
 74.14,
 43.0,
 66.52,
 6.89,
 3.7,
 33.22,
 12.2,
 0,
 66.11,
 30.99,
 55.4,
 79.05,
 42.8,
 42.8,
 59.68,
 73.4,
 79.75,
 80.6,
 39.16,
 0,
 69.75,
 67.3,
 77.43,
 58.53,
 77.0,
 77.22,
 48.99,
 82.33,
 0,
 33.82,
 74.71,
 23.0,
 28.4,
 35.01,
 26.01,
 35.01,
 84.24,
 66.4,
 55.36,
 78.6,
 10.33,
 0,
 82.87,
 75.24,
 91.4,
 74.88,
 35.6,
 78.8,
 60.8,
 41.07,
 59.61,
 0,
 76.28,
 71.6,
 48.2,
 30.0,
 48.0,
 63.34,
 35.6,
 31.23,
 66.0,
 19.26,
 47.64,
 68.0,
 9.09,
 48.99,
 78.8,
 79.5,
 32.0,
 46.4,
 59.0,
 50.0,
 21.02,
 14.72,
 79.72,
 33.8,
 78.69,
 77.0,
 64.47,
 26.55,
 60.8,
 43.0,
 71.82,
 42.01,
 73.24,
 104.0,
 80.89,
 0,
 55.4,
 1.36,
 75.65,
 14.0,
 62.24,
 83.34,
 46.4,
 73.08,
 74.86,
 78.93,
 22.82,
 78.51,
 71.87,
 59.85,
 57.2,
 24.8,
 78.84,
 42.01,
 37.4,
 28.4,
 1.8,
 50.11,
 69.8,
 59.88,
 48.2,
 78.8,
 38.3,
 67.33,
 35.01,
 26.01,
 52.12,
 71.01,
 28.0,
 47.93,
 46.99,
 66.42,
 39.2,
 84.2,
 85.89,
 70.45,
 75.2,
 75.2,
 76.21,
 75.43,
 62.31,
 52.0,
 41.95,
 75.2,
 55.4,
 71.22,
 0,
 23.27,
 73.4,
 78.8,
 78.69,
 42.8,
 41.0,
 36.0,
 12.67,
 70.83,
 8.6,
 72.79,
 59.31,
 32.0,
 35.6,
 30.99,
 73.71,
 21.96,
 55.85,
 59.0,
 80.6,
 30.2,
 77.43,
 9.93,
 88.32,
 50.0]

In [7]:
# Heatmap of temperature

# Get the latitude and longitutde.
locations = city_data_df[['Lat', 'Lng']]


# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.

heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, 
                                max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of percent humidity
locations = city_data_df[['Lat', 'Lng']]
humidity = city_data_df['Humidity']
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False,
                                max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of percent cloudiness
locations = city_data_df[['Lat', 'Lng']]
cloudiness = city_data_df['Cloudiness']
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=cloudiness, dissipating=False,
                                max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Heatmap of percent wind speed
locations = city_data_df[['Lat', 'Lng']]
wind = city_data_df['Wind Speed']
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False,
                                max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Ask the customer to add a minimum adn maximum temperature value.
# min_temp = float(input('What is the minimum temperature you would like for your trip? '))
# max_temp = float(input('What is the maximum temperature you would like for your trip? '))

min_temp = float(45.0)
max_temp = float(60.0)

In [12]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df['Max Temp'] <= max_temp) &
                                       (city_data_df['Max Temp'] >= min_temp)]

preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
13,13,Tepelene,AL,2020-12-02 01:58:16,40.30,20.02,46.99,92,37,1.99
20,20,Mataura,NZ,2020-12-02 01:58:17,-46.19,168.86,57.99,56,100,14.00
21,21,Hermanus,ZA,2020-12-02 01:58:17,-34.42,19.23,57.00,65,70,5.01
26,26,Port Elizabeth,ZA,2020-12-02 01:58:17,-33.92,25.57,59.00,82,90,3.36
28,28,Hasaki,JP,2020-12-02 01:58:17,35.73,140.83,48.20,93,75,10.29
46,46,Half Moon Bay,US,2020-12-02 01:58:19,37.46,-122.43,57.00,66,20,13.87
56,56,Coihaique,CL,2020-12-02 01:58:20,-45.58,-72.07,48.20,84,13,10.29
59,59,Yazd,IR,2020-12-02 01:58:20,31.90,54.37,47.25,75,5,0.58
63,63,San Carlos De Bariloche,AR,2020-12-02 01:55:17,-41.15,-71.31,48.20,61,75,21.92
75,75,Katsuura,JP,2020-12-02 01:58:21,35.13,140.30,51.01,71,75,11.41

In [13]:
preferred_cities_df.count()

City_ID       96
City          96
Country       94
Date          96
Lat           96
Lng           96
Max Temp      96
Humidity      96
Cloudiness    96
Wind Speed    96
dtype: int64

In [14]:
hotel_df = preferred_cities_df[['City', 'Country', 'Max Temp', 'Lat', 'Lng']].copy()
hotel_df['Hotel Name'] = ''
hotel_df.head(10)

                       City Country  Max Temp    Lat     Lng Hotel Name
13                 Tepelene      AL     46.99  40.30   20.02
20                  Mataura      NZ     57.99 -46.19  168.86
21                 Hermanus      ZA     57.00 -34.42   19.23
26           Port Elizabeth      ZA     59.00 -33.92   25.57
28                   Hasaki      JP     48.20  35.73  140.83
46            Half Moon Bay      US     57.00  37.46 -122.43
56                Coihaique      CL     48.20 -45.58  -72.07
59                     Yazd      IR     47.25  31.90   54.37
63  San Carlos De Bariloche      AR     48.20 -41.15  -71.31
75                 Katsuura      JP     51.01  35.13  140.30

In [15]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key}

In [16]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key}
#     "location": "-15.77,128.73"}
# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
# hotels = requests.get(base_url, params=params).json()

# hotels['results'][0]['name']

In [17]:
# # Iterate through the DataFrame.
# for index, row in hotel_df.iterrows():
#     # Get the latitude and longitude.
#     lat = row["Lat"]
#     lng = row["Lng"]

#     # Add the latitude and longitude to location key for the params dictionary.
#     params["location"] = f"{lat},{lng}"

#     # Use the search term: "lodging" and our latitude and longitude.
#     base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
#     # Make request and get the JSON data from the search.
#     hotels = requests.get(base_url, params=params).json()
#     # Grab the first hotel from the results and store the name.
#     hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]

In [18]:
# hotel_df

In [19]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitutde.
    lat = row['Lat']
    lng = row['Lng']
    
    # Add the latitude and longittude to location key for the params dictionary.
    params['location'] = f"{lat},{lng}"
    
#     print(params)
    # Use the search term: 'lodging' and our latitude and longitude.
    base_url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    
    try:
        hotel_df.loc[index, 'Hotel Name'] = hotels['results'][0]['name']
    except (IndexError):
        print("Hotel not found... skipping.")
        
# hotel_df

Hotel not found... skipping.

In [20]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[['Lat', 'Lng']]
max_temp = hotel_df['Max Temp']
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
                                 dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [21]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [22]:
    
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [23]:
# Add a heatmap of temperature for a the vacation spots and a pop-up marker for each city.
locations = hotel_df[['Lat', 'Lng']]
max_temp = hotel_df['Max Temp']
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations,weights=max_temp, dissipating=False,
                                max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))